//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAppLogger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Warning")]
        public global::Microsoft.Extensions.Logging.LogLevel LogLevelMicrosoft {
            get {
                return ((global::Microsoft.Extensions.Logging.LogLevel)(this["LogLevelMicrosoft"]));
            }
            set {
                this["LogLevelMicrosoft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Warning")]
        public global::Microsoft.Extensions.Logging.LogLevel LogLevelSystem {
            get {
                return ((global::Microsoft.Extensions.Logging.LogLevel)(this["LogLevelSystem"]));
            }
            set {
                this["LogLevelSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trace")]
        public global::Microsoft.Extensions.Logging.LogLevel LogLevelWFAppLogger {
            get {
                return ((global::Microsoft.Extensions.Logging.LogLevel)(this["LogLevelWFAppLogger"]));
            }
            set {
                this["LogLevelWFAppLogger"] = value;
            }
        }
    }
}
