//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAppLogger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sample log message")]
        public string DefaultLogMessage {
            get {
                return ((string)(this["DefaultLogMessage"]));
            }
            set {
                this["DefaultLogMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<Root>
  <Logging>
    <LogLevel>
      <WFAppLogger>Trace</WFAppLogger>
      <Default>Debug</Default>
      <Microsoft>Warning</Microsoft>
      <System>Warning</System>
    </LogLevel>
    <File>
      <IncludeScopes>true</IncludeScopes>
      <BasePath>Logs</BasePath>
      <Files>
        <Path>&lt;appname&gt;-&lt;counter:000&gt;.log</Path>
        <MaxFileSize>10000</MaxFileSize>
      </Files>
    </File>
  </Logging>
</Root>")]
        public global::System.Xml.XmlDocument LoggingConfig {
            get {
                return ((global::System.Xml.XmlDocument)(this["LoggingConfig"]));
            }
            set {
                this["LoggingConfig"] = value;
            }
        }
    }
}
